package com.jgeek00.crowdsecmonitor.constants

object StorageKeys {
    const val THEME = "THEME"
    const val TOP_ITEMS_DASHBOARD = "TOP_ITEMS_DASHBOARD"
    const val SHOW_DEFAULT_ACTIVE_DECISIONS = "SHOW_DEFAULT_ACTIVE_DECISIONS"
    const val DISABLE_DECISION_TIMER_ANIMATION = "DISABLE_DECISION_TIMER_ANIMATION"
    const val SHOW_DEFAULT_DECISIONS_GROUPED_BY_IP = "SHOW_DEFAULT_DECISIONS_GROUPED_BY_IP"
    const val ONBOARDING_COMPLETED = "ONBOARDING_COMPLETED"
}
